# Generated by Django 3.0.6 on 2020-05-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milouser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='milouser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
